### PR TITLE
update opentok version

### PR DESCRIPTION
**Pull request by aspin**
as title says

### CODE REVIEW

**Comment by dandv** [comment]
Hey @carlodicelico, is this package necessary now that [Meteor 1.3 can use NPM modules directly](https://guide.meteor.com/1.3-migration.html#modules)?

**Comment by carlodicelico** [comment]
Nope! 😀



On Wed, Jul 27, 2016 at 3:56 AM -0400, "Dan Dascalescu" <notifications@github.com> wrote:












Hey @carlodicelico, is this package necessary now that Meteor 1.3 can use NPM modules directly?

**Comment by carlodicelico** [comment]
No longer necessary.

**Comment by cdcme** [comment]
@aspin Sorry for the delay, but this package is now up-to-date with the latest OpenTok library versions (both the NPM and client).

Developers are encouraged to use the node module directly for future projects, though, since Meteor seems to be embracing NPM nowadays. 🤓

**Pull request closed without merging**
